sudo: false
language: node_js
node_js:
  - "6.5"
  - "7.0.0"
install:
  - npm install
script:
  - npm test
env:
  - CXX=g++-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9