sudo: false
language: node_js
node_js:
  - "8.9.0"
install:
  - npm install
  - npm run configure
script:
  - npm test
env:
  - CXX=g++-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9