version: {build}

image: 
  - Visual Studio 2015
  - Visual Studio 2013

branches:
  only:
  - master
		
platform:
  - x64
  - x86

install:
  - ps: Install-Product node "7.0.0"
  - npm install -g node-gyp
  - node -e "console.log(process.arch);"
  - IF /I "%PLATFORM%" == "x64" set PATH=C:\Python27-x64;%PATH%
  - IF /I "%PLATFORM%" == "x86" SET PATH=C:\python27;%PATH%
  - IF /I "%PLATFORM%" == "x64" CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - IF /I "%PLATFORM%" == "x86" CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - npm install --ignore-scripts

build_script:
  - node-gyp configure
  - node-gyp build

test_script:
  - node --version
  - npm --version
  - npm tst